# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "1.1.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[prune]
  go-tests = true
  unused-packages = true
